apiVersion: v1
entries:
  parallels-devops-service:
  - apiVersion: v2
    appVersion: 0.8.1
    created: "2024-06-10T12:29:19.225277818Z"
    description: Parallels Desktop DevOps Service
    digest: 701b834c78e549128da6356bf606e69f85fa92b4c2a801c106f2e51b7acc2170
    name: parallels-devops-service
    type: application
    urls:
    - https://parallels.github.io/prl-devops-service/charts/parallels-devops-service-0.8.1.tgz
    version: 0.8.1
  - apiVersion: v2
    appVersion: 0.5.4
    created: "2024-06-10T12:29:19.224810687Z"
    description: Parallels Desktop DevOps Service
    digest: c2bc464c67821348b07472a34d54c7dea01cbd503942628e4342df3b699a3f62
    name: parallels-devops-service
    type: application
    urls:
    - https://parallels.github.io/prl-devops-service/charts/parallels-devops-service-0.5.4.tgz
    version: 0.5.4
generated: "2024-06-10T12:29:19.22422213Z"
