version: '3.9'
name: api
services:
  api:
    build: .
    ports:
      - "80:80"
    environment:
      HMAC_SECRET: ''
      LOG_LEVEL: 'info'
      SECURITY_PRIVATE_KEY: ''
      TLS_ENABLED: 'false'
      TLS_PORT: '447'
      TLS_CERTIFICATE: ''
      TLS_PRIVATE_KEY: ''
      API_PORT: '80'
      API_PREFIX: '/api'