apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm.fullname" . }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
data:
  LOG_LEVEL: {{ .Values.logLevel }}
  # TLS_ENABLED: {{ .Values.ingress.tls.enabled }}
  # TLS_PORT: {{ .Values.ingress.tls.port }}
  # TOKEN_DURATION_MINUTES: {{ .Values.security.tokenDurationMinutes }}
  # API_PORT: {{ .Values.ingress.apiPort }}
  API_PREFIX: {{ .Values.ingress.apiPrefix }}