apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm.fullname" . }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
data:
  LOG_LEVEL: {{ .Values.logLevel }}
  TLS_PORT: {{ .Values.ingress.tls.port | quote }}
  TOKEN_DURATION_MINUTES: {{ .Values.security.tokenDurationMinutes | quote }}
  API_PORT: {{ .Values.ingress.apiPort | quote }}
  API_PREFIX: {{ .Values.ingress.apiPrefix }}
  DATABASE_FOLDER: {{ .Values.storage.databasePath }}