apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm.fullname" . }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.security.hmacSecret }}
  HMAC_SECRET: {{ .Values.security.hmacSecret | b64enc }}
  {{- end }}
  {{- if .Values.security.key }}
  SECURITY_PRIVATE_KEY: {{ .Values.security.key | b64enc }}
  {{- end }}
  {{- if .Values.security.rootPassword }}
  SECURITY_ROOT_PASSWORD: {{ .Values.security.rootPassword | b64enc }}
  {{- end }}
  {{- if .Values.ingress.tls.enabled }}
  # TLS_CERTIFICATE: {{ .Values.ingress.tls.certificate }}
  # TLS_PRIVATE_KEY: {{ .Values.ingress.tls.privateKey }}
  {{- end }}
