replicaCount: 1

image:
  repository: cjlapao/pd-api-service
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

storage:
  node_name: ''
  databasePath: '/go/bin/db'

security:
  hmacSecret: ""
  key: ""
  tokenDurationMinutes: 60
  rootPassword: ""

service:
  type: ClusterIP
  port: 80
  targetPort: 80

logLevel: info

config:
  disableCatalogCaching: false

ingress:
  istio: false
  prefix: parallels
  enabled: true
  annotations: {}
  gateway: ""
  host: ""
  apiPort: 80
  apiPrefix: /api
  tls:
    enabled: false
    port: 443
    certificate:
    privateKey:
    

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

