title: Parallels Desktop DevOps Service
brand: Parallels Desktop
brand_url: https://www.parallels.com/products/desktop
brand_img: pl-logo-dk.png
email: support@parallels.com
tagline: "Parallels Desktop DevOps Service"
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/prl-devops-service" # the subpath of your site, e.g. /blog
url: "https://parallels.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  Parallels
permalink: pretty
theme: bulma-clean-theme
remote-theme: chrisrhymes/bulma-clean-theme
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown-parser-gfm
  - jekyll-redirect-from

disqus:
  shortname: parallels

exclude: 
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

livereload: true

sass:
  style: compressed

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      show_sidebar: false
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Parallels Desktop DevOps Service"
      layout: post
      image: /assets/img/new_release_v1.png
      show_sidebar: false

markdown: kramdown
highlighter: rouge
footer_menu: footer
fixed_navbar: true

collections:
  products: 
    output: true