basePath: /api
definitions:
  models.ApiErrorResponse:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
  models.ApiKeyResponse:
    properties:
      created_at:
        type: string
      id:
        type: string
      key:
        type: string
      name:
        type: string
      revoked:
        type: boolean
      revoked_at:
        type: string
      updated_at:
        type: string
    type: object
  models.OAuthErrorResponse:
    properties:
      error:
        $ref: '#/definitions/models.OAuthErrorType'
      error_description:
        type: string
      error_uri:
        type: string
    type: object
  models.OAuthErrorType:
    enum:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    - 12
    type: integer
    x-enum-varnames:
    - OAuthInvalidRequestError
    - OAuthInvalidClientError
    - OAuthInvalidGrant
    - OAuthInvalidScope
    - OAuthUserExists
    - OAuthUnauthorizedClient
    - OAuthUnsupportedGrantType
    - OAuthPasswordMismatch
    - OAuthPasswordValidation
    - OAuthUserValidation
    - OAuthEmailNotVerified
    - OAuthUserBlocked
    - UnknownError
info:
  contact:
    email: carlos.lapao@parallels.com
    name: Parallels Desktop API Support
    url: https://forum.parallels.com/
  description: Parallels Desktop API Service
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Parallels Desktop API
  version: "1.0"
paths:
  /v1/auth/api_keys:
    get:
      description: This endpoint returns all the api keys
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.ApiKeyResponse'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ApiErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/models.OAuthErrorResponse'
      security:
      - ApiKeyAuth: []
      - BearerAuth: []
      summary: Gets all the api keys
      tags:
      - Api Keys
securityDefinitions:
  ApiKeyAuth:
    description: Type the api key in the input below.
    in: header
    name: X-Api-Key
    type: apiKey
  BearerAuth:
    description: Type "Bearer" followed by a space and JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
