name: Bot

on:
  issues: 
    types: [opened, reopened]
  pull_request:
    types: [opened, reopened]

jobs:
  assign-security:
    name: Assign Security Label
    env:
      repo: ${{ github.head_ref }}
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v3
      - name: Assign Security Label
        if: ${{ github.event_name == 'pull_request' && github.event.pull_request.draft == false && contains(github.event.pull_request.title, 'security')}}
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr edit ${{ github.event.number }} --add-label "security"
      - name: Assign Security Label
        if: ${{ github.event_name == 'issue' && contains(github.event.issue.title, 'security')}}
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh issue edit ${{ github.event.issue.number }} --add-label "security"