name: Pull Request

on:
  pull_request:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Go 1.21.x
        uses: actions/setup-go@v4
        with:
          # Semantic version range syntax or exact version of Go
          go-version: '1.21.x'
          cache-dependency-path: go.sum
      - name: Install dependencies
        run: |
          go get .
      - name: Run tests
        run: go test -v ./...
      - name: Build
        run: go build -v ./...