name: Create release PR

run-name: Create release PR for new ${{ github.event.inputs.version }} version

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: choice
        description: "What type of release is this"
        options:
          - "major"
          - "minor"
          - "patch"

jobs:
  create-release-pr:
    name: Create release PR

    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    env:
      new_version: ""
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
        
      - name: Bump version and push
        run: |
          git config --global user.email "cjlapao@gmail.com"
          git config --global user.name "cjlapao"

          NEW_VERSION=$(./scripts/workflows/increment-version.sh ${{ inputs.version }})
          jq --arg new_version "$NEW_VERSION" '.version = $new_version' version.json > "tmp.json" && mv "tmp.json" "version.json"
          
          git checkout -b release/$NEW_VERSION
          sed -i '/^var ver =/c\var ver = "$NEW_VERSION"' main.go

          git add version.json main.go
          git commit -m "Release extension version $NEW_VERSION"

          git push --set-upstream origin release/$NEW_VERSION

          echo "new_version=$NEW_VERSION" >> $GITHUB_ENV

      - name: Create PR
        run: |
          LAST_PR=$(gh pr list --repo ${{ github.repository }} --limit 1 --state merged --search "Release version" --json number | jq -r '.[0].number')
          ./scripts/workflows/generate-release-notes.sh $LAST_PR ${{ env.new_version }}
          gh pr create \
            --title "Release version ${{ env.new_version }}" \
            --body-file releasenotes.md \
            --base main \
            --head release/${{ env.new_version }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}